# A quick CS101

## What is a computer?

Modern computer can be defined as

> machines that store and manipulate information under the control of a changeable program.

Two key elements:

* Machines for manipulating information
* Control by a changeable program

## What is a computer program?

* A detailed, step-by-step set of instructions telling a computer what to do.
* If we change the program, the computer performs a different set of actions or a different task.
* The machine stays the same, but the program changes!

* Programs are *executed*, or carried out.

---

* Software (programs) rule the hardware (the physical machine).
* The process of creating this software is called *programming*.

## Algorithm

* One way to show a particular problem can be solved is to actually design a solution.

* This is done by developing an algorithm, a step-by-step process for achieving the desired result.

## Hardware Basics

* The central processing unit (CPU) is the “brain” of a computer.
    + The CPU carries out all the basic operations on the data.
    + Examples: simple arithmetic operations, testing to see if two numbers are equal.

---

* Memory stores programs and data.
    + CPU can only directly access information stored in main memory (RAM or Random Access Memory).
    + Main memory is fast, but volatile, i.e. when the power is interrupted, the contents of memory are lost.
    + Secondary memory provides more permanent storage: magnetic (hard drive, floppy), optical (CD, DVD), flash (SSD)

---

* I/O 
    + Input devices: Information is passed to the computer through keyboards, mice, etc.
    + Output devices: Processed information is presented to the user through the monitor, printer, etc.

---

* Fetch-Execute Cycle
    + First instruction retrieved from memory
    + Decode the instruction to see what it represents
    + Appropriate action carried out.
    + Next instruction fetched, decoded, and executed.

## Programming Languages

Natural language has ambiguity and imprecision problems when used to describe complex algorithms.

* Programs are expressed in an unambiguous, precise way using programming languages.
* Every structure in programming language has a precise form, called its *syntax*.
* Every structure in programming language has a precise meaning, called its *semantics*.

---

* Programmers will often refer to their program as computer code.
* Process of writing an algorithm in a programming language often called coding.

## Low-level Languages

Computer hardware can only understand a very low level language known as *machine language*.

* Example: add two numbers in ARM assembly
```
    @ Load the first number in memory address 0x2021 into register R0
    ldr r0, 0x2021
    ldr r0, [r0]

    @ Load the second number in memory address 0x2022 into register R1
    ldr r1, 0x2022
    ldr r1, [r1]

    @ Add the numbers in R0 and R1 and store the result in R2
    add r2, r0, r1

    @ Store the result in memory address 0x2023
    ldr r3, 0x2023
    str r2, [r3]
```    

---

In reality, these low-level instructions are represented in binary (1’s and 0’s)

## High-level Languages

Designed to be used and understood by humans

```julia
c = a + b
```
* This needs to be translated into the machine language that the computer can execute.
* *Compilers* convert programs written in a high-level language (source code) into the target machine language.
    + Fortran, C/C++, Java, Go, Swift

---

* *Interpreters* simulate a computer that understands a high-level language.
* The source code is not translated into machine language all at once.
* An interpreter analyzes and executes the source code instruction by instruction.
* Interpreted languages are part of a more flexible programming environment since they can be developed and run *interactively*, at the expense of slower execution time than compiled languages.
    + Commandline shells, Lisp, R, Python, Julia

## Dynamic Languages

<!--
[The Life of a Bytecode Language](https://betterprogramming.pub/the-life-of-a-bytecode-language-fca666928e7b)
-->

* A dynamic programming language is a class of high-level programming languages, which at *runtime* can change the behavior of the program by adding new code.
   + Also called a *scripting language*

* Most dynamic languages are interpreted languages, providing an interactive read-eval-print loop (*REPL*). 

* Traditional interpreters *parse* the source code into an intermediate representation (IR) such as an abstract syntax tree (AST) and execute predetermined routines.

## Just-in-time Compilation

* Modern interpreters *compiles* the parsed IR to native machine code at runtime. If the same part of the source code (e.g., function) is executed again, then the compiled native code is executed. This technique is called *just-in-time (JIT) compilation*.
    + For subsequent uses (e.g., calling the function within a loop), the speedup is significant.

* More and more interpreter languages are adopting JIT technology: R (version 3.4+), MATLAB (R2015b+), Python (PyPy), Julia, ...

---

* Distinction between complier and interpreter languages is getting blurred due to improved computation capabilities of the modern hardware and advanced compiler techniques.

# Julia

<img src="./julia_logo.png" align="center" width="400"/>

## What's Julia?

> Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments.

- Project started in 2009. First public release in 2012 
    + Creators: Jeff Bezanson, Alan Edelman, Stefan Karpinski, Viral Shah
- First major release: v1.0 on Aug 8, 2018
- Current stable release: v1.9.3 (August 24, 2023)

---

* Aim to solve the notorious **two language problem**: Prototype code goes into high-level languages like R/Python, production code goes into low-level language like C/C++. 

* Julia aims to:

> Walks like Python. Runs like C.

* Write high-level, abstract code that closely resembles mathematical formulas
    - yet produces fast, low-level machine code that has traditionally only been generated by static languages.


---

![<https://julialang.org/benchmarks/>](https://julialang.org/assets/images/benchmarks.svg)

## Some basic Julia code

In [1]:
# an integer, same as int in R
y = 1
typeof(y) 

Int64

In [2]:
# a Float64 number, same as double in R
y = 1.0
typeof(y) 

Float64

In [3]:
# Greek letters:  `\pi<tab>`
π

π = 3.1415926535897...

In [4]:
typeof(π)

Irrational{:π}

In [5]:
# Greek letters:  `\theta<tab>`
θ = y + π

4.141592653589793

---

In [6]:
# emoji! `\:kissing_cat:<tab>`
😽 = 5.0

5.0

In [7]:
# `\alpha<tab>\hat<tab>`
α̂ = π

π = 3.1415926535897...

In [8]:
# vector of Float64 0s
x = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [9]:
# vector Int64 0s
x = zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

---

In [10]:
# matrix of Float64 0s
x = zeros(5, 3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [11]:
# matrix of Float64 1s
x = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [12]:
# define array without initialization
x = Matrix{Float64}(undef, 5, 3)

5×3 Matrix{Float64}:
 2.23823e-314  2.23823e-314  2.23823e-314
 2.23823e-314  2.23823e-314  2.23823e-314
 2.23823e-314  2.23823e-314  2.23823e-314
 2.23823e-314  2.23823e-314  2.23823e-314
 2.23823e-314  2.23823e-314  2.23823e-314

---

In [13]:
# fill a matrix by 0s
fill!(x, 0)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [14]:
x

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
# initialize an array to be constant 2.5
fill(2.5, (5, 3))

5×3 Matrix{Float64}:
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5
 2.5  2.5  2.5

---

In [16]:
# rational number
a = 3//5

3//5

In [17]:
typeof(a)

Rational{Int64}

In [18]:
b = 3//7

3//7

In [19]:
a + b

36//35

---

In [20]:
# uniform [0, 1) random numbers
x = rand(5, 3)

5×3 Matrix{Float64}:
 0.917222  0.492968   0.506997
 0.564369  0.705425   0.594361
 0.989855  0.254588   0.626454
 0.929263  0.384029   0.420757
 0.749851  0.0123611  0.110815

In [21]:
# uniform random numbers (in Float16)
x = rand(Float16, 5, 3)

5×3 Matrix{Float16}:
 0.575   0.6143  0.672
 0.508   0.6143  0.956
 0.1787  0.6953  0.5127
 0.951   0.4902  0.9736
 0.1094  0.294   0.4346

In [22]:
# random numbers from {1,...,5}
x = rand(1:5, 5, 3)

5×3 Matrix{Int64}:
 5  4  2
 4  1  1
 3  4  4
 3  2  2
 2  5  1

---

In [23]:
# standard normal random numbers
x = randn(5, 3)

5×3 Matrix{Float64}:
 -1.35588   -2.07941   -0.0943297
  1.48426   -2.36824   -0.121338
 -0.417874  -0.885322   0.794723
 -0.51738   -0.741182  -0.652738
  0.80346    1.51982    0.00194865

In [24]:
# range
1:10

1:10

In [25]:
typeof(1:10)

UnitRange{Int64}

In [26]:
1:2:10

1:2:9

In [27]:
typeof(1:2:10)

StepRange{Int64, Int64}

---

In [28]:
# integers 1-10
x = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [29]:
# or equivalently
[1:10...]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

---

In [30]:
# Float64 numbers 1-10
x = collect(1.0:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [31]:
# convert to a specific type
convert(Vector{Float64}, 1:10)

10-element Vector{Float64}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

## Matrices and vectors

### Dimensions

In [1]:
x = randn(5, 3)

5×3 Matrix{Float64}:
 -1.10531   -1.12618   -0.280221
 -0.346053   1.31651    0.0732267
  0.742706   0.135561  -0.994282
 -1.70301   -0.727118   2.31766
  0.745916  -1.12055    0.140907

In [2]:
size(x)

(5, 3)

In [3]:
size(x, 1) # nrow() in R

5

In [4]:
size(x, 2) # ncol() in R

3

In [5]:
# total number of elements
length(x)

15

---

### Indexing

In [6]:
# 5 × 5 matrix of random Normal(0, 1)
x = randn(5, 5)

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   1.01683    1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

In [7]:
# first column
x[:, 1]

5-element Vector{Float64}:
 -0.3840786272805249
  1.563770258704395
 -0.6874461657292189
  0.5631993022368884
  0.5986762237099348

---

In [8]:
# first row
x[1, :]

5-element Vector{Float64}:
 -0.3840786272805249
  0.5406293111966782
  0.003503004059083037
 -0.05344542595632667
  0.3825449134563247

In [9]:
# sub-array
x[1:2, 2:3]

2×2 Matrix{Float64}:
 0.540629  0.003503
 0.876571  1.01683

---

In [10]:
# getting a subset of a matrix creates a copy, but you can also create "views"
z = view(x, 1:2, 2:3)

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 0.540629  0.003503
 0.876571  1.01683

In [11]:
# same as
@views z = x[1:2, 2:3]

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 0.540629  0.003503
 0.876571  1.01683

In [12]:
# change in z (view) changes x as well
z[2, 2] = 0.0
x

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   0.0        1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

---

In [13]:
# y points to same data as x
y = x

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   0.0        1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

In [14]:
# x and y point to same data
pointer(x), pointer(y)

(Ptr{Float64} @0x000000010df5b890, Ptr{Float64} @0x000000010df5b890)

In [15]:
# changing y also changes x
y[:, 1] .= 0  # Dot broadcasting: "vectorization" in Julia. More below
x

5×5 Matrix{Float64}:
 0.0   0.540629   0.003503  -0.0534454   0.382545
 0.0   0.876571   0.0        1.84941     0.567994
 0.0   0.313884  -0.306218  -1.77579    -0.088558
 0.0  -1.18005   -0.895966   0.217129    0.816159
 0.0  -1.44407    0.318821  -0.211098   -0.322778

---

In [16]:
# create a new copy of data
z = copy(x)

5×5 Matrix{Float64}:
 0.0   0.540629   0.003503  -0.0534454   0.382545
 0.0   0.876571   0.0        1.84941     0.567994
 0.0   0.313884  -0.306218  -1.77579    -0.088558
 0.0  -1.18005   -0.895966   0.217129    0.816159
 0.0  -1.44407    0.318821  -0.211098   -0.322778

In [17]:
pointer(x), pointer(z)  # they should be different now

(Ptr{Float64} @0x000000010df5b890, Ptr{Float64} @0x000000010dee4ef0)

---

### Concatenate matrices

In [26]:
# 1-by-3 array
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [27]:
# 3-by-1 vector
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

---

In [28]:
# multiple assignment by tuple
x, y, z = randn(5, 3), randn(5, 2), randn(3, 5)

([0.5893655425511126 0.6478463785075559 0.03675617824627964; 0.32449020240765014 -1.3163416879826713 0.7448429375816905; … ; 1.194345878009456 -0.9709295240318928 0.27695790432451756; -0.22659842128747293 0.1532435439941793 -0.2784639103102133], [1.2488575126330914 -0.8703644138107955; 0.12338420649841966 1.651334800014632; … ; 0.8705337197294406 0.6799072095463546; -1.6574340081943586 -0.3700243675300325], [0.03348929176386288 0.12239273748998791 … -1.6728049527623698 0.5027256700275959; -0.3717281295214447 -0.5438233836426857 … -0.7034641699877021 1.3487199200482247; 0.049027792124969646 0.23817850370798085 … -0.5161662385770864 -0.08535374403107002])

In [29]:
[x y] # 5-by-5 matrix

5×5 Matrix{Float64}:
  0.589366   0.647846   0.0367562   1.24886   -0.870364
  0.32449   -1.31634    0.744843    0.123384   1.65133
 -1.50004   -0.471809  -0.557907    0.278123   1.56953
  1.19435   -0.97093    0.276958    0.870534   0.679907
 -0.226598   0.153244  -0.278464   -1.65743   -0.370024

---

In [30]:
[x y; z] # 8-by-5 matrix

8×5 Matrix{Float64}:
  0.589366    0.647846   0.0367562   1.24886   -0.870364
  0.32449    -1.31634    0.744843    0.123384   1.65133
 -1.50004    -0.471809  -0.557907    0.278123   1.56953
  1.19435    -0.97093    0.276958    0.870534   0.679907
 -0.226598    0.153244  -0.278464   -1.65743   -0.370024
  0.0334893   0.122393   1.5489     -1.6728     0.502726
 -0.371728   -0.543823  -0.71427    -0.703464   1.34872
  0.0490278   0.238179   0.122957   -0.516166  -0.0853537

---

### Dot operation

In Julia, any function `f(x)` can be applied elementwise to an array `X` with the “dot call” syntax `f.(X)`. 

In [31]:
x = randn(5, 3)

5×3 Matrix{Float64}:
  0.311722  -0.602978   -1.41185
 -2.95531    1.06727     2.73063
 -1.4536    -1.68355    -0.195356
  0.728974   0.0607037  -1.21232
 -1.16299   -0.388626    1.52238

In [32]:
y = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

---

In [33]:
x .* y # same as x * y in R

5×3 Matrix{Float64}:
  0.311722  -0.602978   -1.41185
 -2.95531    1.06727     2.73063
 -1.4536    -1.68355    -0.195356
  0.728974   0.0607037  -1.21232
 -1.16299   -0.388626    1.52238

In [34]:
x .^ (-2) # same as x^(-2) in R

5×3 Matrix{Float64}:
 10.2912      2.7504     0.501673
  0.114497    0.877916   0.134114
  0.473274    0.352816  26.2028
  1.88181   271.375      0.680402
  0.739343    6.6212     0.431474

In [35]:
sin.(x)  # same as sin(x) in R

5×3 Matrix{Float64}:
  0.306698  -0.567098   -0.987395
 -0.185207   0.875885    0.399488
 -0.99314   -0.99365    -0.194116
  0.666105   0.0606664  -0.936433
 -0.917994  -0.378917    0.998828

---

### Basic linear algebra

In [36]:
x = randn(5)

5-element Vector{Float64}:
 0.34146810589642673
 1.4981812185148902
 0.25078117390294813
 0.8568548966734539
 0.2612026843555233

In [37]:
using LinearAlgebra
norm(x) # vector L2 norm

1.7962365613435223

In [38]:
# same as
sqrt(sum(abs2, x))

1.7962365613435223

In [39]:
y = randn(5) # another vector
# dot product
dot(x, y) # x' * y

-0.24788199560261587

In [40]:
# same as
x'y

-0.24788199560261587

---

In [41]:
x, y = randn(5, 3), randn(3, 2)
# matrix multiplication, same as %*% in R
x * y

5×2 Matrix{Float64}:
  1.22666    -3.08629
  0.0207958  -1.48039
  1.37031     0.290835
 -2.12267    -0.710753
 -1.52756    -1.22875

In [42]:
x = randn(3, 3)

3×3 Matrix{Float64}:
 -0.821948  -0.417438   0.164008
 -0.117837   1.70361    0.804793
  0.214691  -0.0478425  0.750179

In [43]:
# conjugate transpose
x'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.821948  -0.117837   0.214691
 -0.417438   1.70361   -0.0478425
  0.164008   0.804793   0.750179

In [44]:
b = rand(3)
x'b # same as x' * b

3-element Vector{Float64}:
 -0.35187236916572584
  0.9070636015135449
  1.1667751942065532

---

In [45]:
# trace
tr(x)

1.631839797585085

In [46]:
det(x)

-1.2501936512996823

In [47]:
rank(x)

3

---

### Sparse matrices

In [48]:
using SparseArrays

# 10-by-10 sparse matrix with sparsity 0.1
X = sprandn(10, 10, .1)

10×10 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅   -2.05379   ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅   -1.12422  0.495726
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 

---

In [49]:
# convert to dense matrix; be cautious when dealing with big data
Xfull = convert(Matrix{Float64}, X)

10×10 Matrix{Float64}:
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  -2.05379  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0  -1.12422  0.495726
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0

In [50]:
# convert a dense matrix to sparse matrix
sparse(Xfull)

10×10 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅   -2.05379   ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅   -1.12422  0.495726
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 

---

In [51]:
# syntax for sparse linear algebra is the same as dense linear algebra
β = ones(10)
X * β

10-element Vector{Float64}:
  0.0
 -2.0537854136532983
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.6284968672903815
  0.0

In [52]:
# many functions apply to sparse matrices as well
sum(X)

-2.6822822809436797

## Control flow and loops

* if-elseif-else-end

```julia
if condition1
    # do something
elseif condition2
    # do something
else
    # do something
end
```

* `for` loop

```julia
for i in 1:10
    println(i)
end
```

---

* Nested `for` loop:

```julia
for i in 1:10
    for j in 1:5
        println(i * j)
    end
end
```
Same as

```julia
for i in 1:10, j in 1:5
    println(i * j)
end
```

* Exit loop:

```julia
for i in 1:10
    # do something
    if condition1
        break # skip remaining loop
    end
end
```

---

* Exit iteration:  

```julia
for i in 1:10
    # do something
    if condition1
        continue # skip to next iteration
    end
    # do something
end
```

## Functions 

* Function definition
```julia
function func(req1, req2; key1=dflt1, key2=dflt2)
    # do stuff
    return out1, out2, out3
end
```
- **Required arguments** are separated with a comma and use the positional notation.  
- **Optional arguments** need a default value in the signature.  
- **return** statement is optional (value of the last expression is the return value, like R).  
- Multiple outputs can be returned as a **tuple**, e.g., `return out1, out2, out3`.  

---

* In Julia, all arguments to functions are [**passed by reference**](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_reference), in contrast to R and Matlab (which use pass by value).
    - Implication: function arguments can be **modified** inside the function.

* By convention function names ending with `!` indicates that function mutates at least one argument, typically the first.
```julia
sort!(x) # vs sort(x)
```

* Anonymous functions, e.g., `x -> x^2`, is commonly used in collection function or list comprehensions.
```julia
map(x -> x^2, y) # square each element in x
```

---

* Functions can be nested:

```julia
function outerfunction()
    # do some outer stuff
    function innerfunction()
        # do inner stuff
        # can access prior outer definitions
    end
    # do more outer stuff
end
```

* Functions can be vectorized using the "dot call" syntax:

In [53]:
function myfunc(x)
    return sin(x^2)
end

x = randn(5, 3)
myfunc.(x)

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

---

### Collection function

Like a series of `apply` functions in R.

Apply a function to each element of a collection:

```julia
map(f, coll) # or
map(coll) do elem
    # do stuff with elem
    # must contain return
end
```

Alternative "vectorization":

In [54]:
map(x -> sin(x^2), x)   # same as above

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

---

In [55]:
map(x) do elem   # long version of above
    elem = elem^2
    return sin(elem)
end

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

In [56]:
# Mapreduce
mapreduce(x -> sin(x^2), +, x)   # mapreduce(mapper, reducer, data)

3.2908069925088776

In [57]:
# same as
sum(x -> sin(x^2), x)

3.2908069925088776

---

### List comprehension

In [58]:
[sin(2i + j) for i in 1:5, j in 1:3] # similar to Python

5×3 Matrix{Float64}:
  0.14112   -0.756802  -0.958924
 -0.958924  -0.279415   0.656987
  0.656987   0.989358   0.412118
  0.412118  -0.544021  -0.99999
 -0.99999   -0.536573   0.420167

## Type system

* Every variable in Julia has a type.

* Everything is a subtype of the abstract type `Any`.

* An abstract type defines a set of types. 

---

* Consider types in Julia that are a `Number`:

<img src="1280px-Type-hierarchy-for-julia-numbers.png" width="1280" align="center"/>
<https://en.wikibooks.org/wiki/Introducing_Julia/Types>

---

* We can explore type hierarchy with `typeof()`, `supertype()`, and `subtypes()`.

In [59]:
typeof(1.0), typeof(1)

(Float64, Int64)

In [60]:
supertype(Float64)

AbstractFloat

In [61]:
subtypes(AbstractFloat)

4-element Vector{Any}:
 BigFloat
 Float16
 Float32
 Float64

In [62]:
# Is Float64 a subtype of AbstractFloat?
Float64 <: AbstractFloat

true

In [63]:
# On 64bit machine, Int == Int64
Int == Int64

true

---

In [64]:
# convert to Float64
convert(Float64, 1)

1.0

In [65]:
# same as
Float64(1)

1.0

In [66]:
# Float32 vector
x = randn(Float32, 5)

5-element Vector{Float32}:
 -0.6000053
  0.57898515
 -1.9387985
 -0.04535096
  0.9868613

In [67]:
# convert to Float64
convert(Array{Float64}, x)

5-element Vector{Float64}:
 -0.6000053286552429
  0.5789851546287537
 -1.9387985467910767
 -0.04535096138715744
  0.9868612885475159

---

In [68]:
# same as
Float64.(x)

5-element Vector{Float64}:
 -0.6000053286552429
  0.5789851546287537
 -1.9387985467910767
 -0.04535096138715744
  0.9868612885475159

In [69]:
# convert Float64 to Int64
convert(Int, 1.0)

1

In [70]:
convert(Int, 1.5) # should use round(1.5)

LoadError: InexactError: Int64(1.5)

In [71]:
round(Int, 1.5)

2

## Multiple dispatch

* [Multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch) is a feature of some programming languages in which a function or method can be dynamically dispatched based on the run time (dynamic) type or, in the more general case, some other attribute of more than one of its arguments.

* Multiple dispatch lies in the core of Julia design. It allows built-in and user-defined functions to be overloaded for different combinations of argument types.

* In Juila, methods belong to functions, called **generic functions**.

---

* Let's consider a simple "doubling" function:

In [2]:
g(x) = x + x

g (generic function with 1 method)

* This definition is too broad, since some things, e.g., strings, cannot be added.

In [4]:
g(1.5)

3.0

In [3]:
g("hello world")

LoadError: MethodError: no method matching +(::String, ::String)
String concatenation is performed with * (See also: https://docs.julialang.org/en/v1/manual/strings/#man-concatenation).

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:578


---

In [6]:
g(x::Float64) = x + x

g (generic function with 2 methods)

* This definition is correct but too restrictive, since any `Number` can be added.

In [7]:
g(x::Number) = x + x

g (generic function with 3 methods)

* This definition will automatically work on the entire type tree above!

* A lot nicer than 
```julia
function g(x)
    if isa(x, Number)
        return x + x
    else
        throw(ArgumentError("x should be a number"))
    end
end
```

---

`methods(func)`  displays all methods defined for `func`.

In [8]:
methods(g)

# 3 methods for generic function "g" from Main:
 [1] g(x::Float64)
     @ In[6]:1
 [2] g(x::Number)
     @ In[7]:1
 [3] g(x)
     @ In[2]:1

When calling a function with multiple definitions, Julia will search from the narrowest signature to the broadest signature.

---

* `@which func(x)` marco tells which method is being used for argument signature `x`.

In [78]:
# an Int64 input
@which g(1)

g(x::Number) in Main at In[76]:1

In [79]:
@which g(1.0)

g(x::Float64) in Main at In[75]:1

In [80]:
# a Vector{Float64} input
@which g(randn(5))

g(x) in Main at In[72]:1

* R also makes use of generic functions and multiple dispatch (see <http://adv-r.had.co.nz/OO-essentials.html#s3>), but it is not fully optimized.

## JIT

* Julia's efficiency results from its capability to *infer the types* of all variables within a function and then call LLVM (compiler) to generate optimized machine code at run-time. 

Consider the `g` (doubling) function defined earlier. This function will work on **any** type which has a method for `+`.

In [81]:
g(2), g(2.0)

(4, 4.0)

**Step 1**: Parse Julia code into AST.

In [82]:
@code_lowered g(2)

CodeInfo(
1 ─ %1 = x + x
└──      return %1
)

---

**Step 2**: Type inference according to input type.

In [83]:
@code_warntype g(2)

Variables
  #self#::Core.Const(g)
  x::Int64

Body::Int64
1 ─ %1 = (x + x)::Int64
└──      return %1


In [84]:
@code_warntype g(2.0)

Variables
  #self#::Core.Const(g)
  x::Float64

Body::Float64
1 ─ %1 = (x + x)::Float64
└──      return %1


---

**Step 3**: Compile into **LLVM bytecode** 

In [85]:
@code_llvm g(2)

;  @ In[76]:1 within `g'
define i64 @julia_g_4079(i64 signext %0) {
top:
; ┌ @ int.jl:87 within `+'
   %1 = shl i64 %0, 1
; └
  ret i64 %1
}


In [86]:
@code_llvm g(2.0)

;  @ In[75]:1 within `g'
define double @julia_g_4104(double %0) {
top:
; ┌ @ float.jl:326 within `+'
   %1 = fadd double %0, %0
; └
  ret double %1
}


---

We didn't provide a type annotation. But different LLVM code gets generated depending on the argument type!

* In R or Python, `g(2)` and `g(2.0)` would use the same code for both.
 
* In Julia, `g(2)` and `g(2.0)` dispatch to optimized code for `Int64` and `Float64`, respectively.

For integer input `x`, LLVM compiler is smart enough to know `x + x` is simple shifting `x` by 1 bit, which is faster than addition.

---

* **Step 4**: Lowest level is the **assembly code**, which is machine dependent.

In [87]:
@code_native g(2)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[76]:1 within `g'
; │┌ @ int.jl:87 within `+'
	leaq	(%rdi,%rdi), %rax
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └


1st instruction adds the content of the general purpose 64-bit register (a small memory inside the CPU) RDI to itself, and load the result into another register RAX. The addition here is the integer arithmetic.

---

In [88]:
@code_native g(2.0)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[75]:1 within `g'
; │┌ @ float.jl:326 within `+'
	vaddsd	%xmm0, %xmm0, %xmm0
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └
